- description: null
  label: "Reviews"
  name: "reviews"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: false
  parent: null
  fields:
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "is_feature_clipped"
      label: "Clip Featured Image"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "jump_nav"
      label: "Jump Nav"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "show_related_posts"
      label: "Show Related Posts"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "related_posts_1"
      label: "Related Posts 1"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "related_posts_2"
      label: "Related Posts 2"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "related_posts_3"
      label: "Related Posts 3"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
- description: null
  label: "Reviews Post"
  name: "reviews_post"
  sort: 1
  listed: true
  hasRoute: true
  showAsTable: true
  parent: "reviews"
  fields:
    - name: "sub_text"
      label: "List Summary"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "header_text"
      label: "Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "sub_header"
      label: "Sub Heading"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_image"
      label: "Featured Image"
      description: null
      datatype: "images"
      sort: 1
      required: null
      relationship: null
      settings:
        limit: 1
        list: false
    - name: "is_feature_clipped"
      label: "Clip Featured Image"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "featured_image_alt"
      label: "Featured Image Alt Text"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "featured_video"
      label: "Featured Video"
      description: null
      datatype: "text"
      sort: 1
      required: true
      relationship: null
    - name: "schemamarkup"
      label: "Schema Markup"
      description: null
      datatype: "textarea"
      sort: 1
      required: true
      relationship: null
    - name: "jump_nav"
      label: "Jump Nav"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
    - name: "show_related_posts"
      label: "Show Related Posts"
      description: null
      datatype: "yes_no"
      sort: 1
      required: true
      relationship: null
      settings:
        list: true
        options:
          0: "No"
          1: "Yes"
    - name: "related_posts_1"
      label: "Related Posts 1"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "related_posts_2"
      label: "Related Posts 2"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "related_posts_3"
      label: "Related Posts 3"
      description: null
      datatype: "internal_link"
      sort: 1
      required: true
      relationship: null
    - name: "body"
      label: "Body"
      description: null
      datatype: "wysiwyg_basic"
      sort: 1
      required: true
      relationship: null
